from app.magic.Errors import MagicException


class TestError(MagicException):
    pass
